# cloudbuild.yaml for macrophage atac.
# This file is used by the Cloud Build trigger that builds this image.

steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/t-cell-activation-atac:$COMMIT_SHA
  - --cache=true
  - --cache-ttl=720h
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
      [
        'run',
        'deploy',
        't-cell-activation-atac',
        '--image',
        'gcr.io/$PROJECT_ID/t-cell-activation-atac:$COMMIT_SHA',
        '--region',
        'us-west1',
        '--platform',
        'managed',
        '--quiet',
      ]
